# Generated by Django 5.0.6 on 2024-07-03 05:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('precio', models.FloatField(default=0.0, max_length=10)),
                ('imagen', models.ImageField(blank=True, default='productos/producto-default.png', null=True, upload_to='Productos/')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=400, null=True, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
