# Generated by Django 5.0.6 on 2024-07-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(default='/img', upload_to='comics/'),
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
